### ISSUE TITLE
Support for CPT 'taxonomies'  => array( 'category' ),

### ISSUE THREAD

**Issue by aaroneight** [soberwp/models#3]
It seems that the CPT YAML doesn't support the `'taxonomies'  => array( 'category' ),` declartion for a CPT.  In other words, using the default "category" for a new CPT.

**Comment by darrenjacoby** [comment]
@aaroneight have you tried https://github.com/soberwp/models#taxonomy-tips ? 

https://github.com/soberwp/models/blob/master/.github/yaml/taxonomy-multiple.yaml

**Comment by darrenjacoby** [comment]
This should work. 

```yaml
---
type: cpt
name: book
supports:
- title
- editor
config:
  taxonomies:
    - category
    - tag
```
